version: '3.9'

services:
  mysql:
    container_name: mysql
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      # - ./mysql:/var/lib/mysql
      - ./sql_project:/sql_project
    ports:
      - "3306:3306"
