USE Wifly;

-- EXPORTACIÓN CSV
SELECT * FROM AREAS
INTO OUTFILE '/Uploads/areas.csv'
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\r\n';

SELECT * FROM TIPO_DE_PAGO
INTO OUTFILE '/Uploads/tipo_de_pago.csv'
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\r\n';

SELECT * FROM ABONOS
INTO OUTFILE '/Uploads/abonos.csv'
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\r\n';

SELECT * FROM PROVEEDORES
INTO OUTFILE '/Uploads/proveedores.csv'
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\r\n';

SELECT * FROM EQUIPOS
INTO OUTFILE '/Uploads/equipos.csv'
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\r\n';

SELECT * FROM CLIENTES
INTO OUTFILE '/Uploads/clientes.csv'
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\r\n';

SELECT * FROM EMPLEADOS
INTO OUTFILE '/Uploads/empleados.csv'
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\r\n';

SELECT * FROM FACTURAS
INTO OUTFILE '/Uploads/facturas.csv'
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\r\n';

SELECT * FROM OPERACIONES
INTO OUTFILE '/Uploads/operaciones.csv'
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\r\n';

SELECT * FROM ASIGNACIONES
INTO OUTFILE '/Uploads/asignaciones.csv'
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\r\n';

SELECT * FROM SUMINISTROS
INTO OUTFILE '/Uploads/suministros.csv'
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\r\n';

SELECT * FROM VENTAS
INTO OUTFILE '/Uploads/ventas.csv'
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\r\n';
